name: Markedly
version: '0.1.0'
summary: A tiny, crappy, markdown editor
description: |
  A markdeown editor that is not very good, but it works. It is written in Go and uses Fyne for the GUI.

grade: stable
confinement: strict

apps:
  Markedly:
    command: Markedly

parts:
  Markedly:
    plugin: go
    go-importpath: github.com/TylerCode/Markedly
    source: .